name: JavaScript CI
on:
  push:
    branches:
      - main

jobs:
  run-javascript:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: print node version
        run: node --version

      - name: execute javascript
        run: node app.js
